#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Convert avatar/jollybot.gif into avatar/happy_anim.c for the ST7789 display backend.

The GIF is pixel art drawn on a 5-pixel grid (4x4 block plus a 1-pixel gap).
This samples one colour per art pixel, crops to the area the animation uses,
and emits palette indices plus an RGB565 palette. The firmware scales each art
pixel back up to a solid block.

Usage: gen_happy_anim.py avatar/jollybot.gif   (requires Pillow)
"""

import pathlib
import sys

from PIL import Image

GRID = 5
# Art-pixel crop, chosen so 3x scaling fits the 170-pixel panel width. The
# dropped edge columns only hold sparkle tips in a few frames.
CROP_X, CROP_Y, WIDTH, HEIGHT = 4, 0, 56, 59

OUT = pathlib.Path(__file__).resolve().parent.parent / "avatar" / "happy_anim.c"

HEADER = [
    '// Copyright (c) Meta Platforms, Inc. and affiliates.',
    '',
]


def rgb565_be(rgb):
    r, g, b = rgb
    v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    # Panel expects the most significant byte first.
    return ((v & 0xFF) << 8) | (v >> 8)


def main():
    gif = Image.open(sys.argv[1])
    palette = {}
    frames = []
    durations = set()
    for i in range(gif.n_frames):
        gif.seek(i)
        durations.add(gif.info.get("duration", 40))
        px = gif.convert("RGB").load()
        frame = []
        for y in range(HEIGHT):
            for x in range(WIDTH):
                c = px[(CROP_X + x) * GRID, (CROP_Y + y) * GRID]
                frame.append(palette.setdefault(c, len(palette)))
        frames.append(frame)
    if len(palette) > 256 or len(durations) != 1:
        sys.exit(f"unsupported GIF: {len(palette)} colours, durations {durations}")

    lines = HEADER + [
        "// Generated by tools/gen_happy_anim.py from jollybot.gif. Do not edit.",
        '#include "happy_anim.h"',
        "",
        "#if CONFIG_HOMEHUB_DISPLAY",
        "",
        f"const uint16_t happy_anim_palette[{len(palette)}] = {{",
    ]
    for c in palette:
        lines.append(f"    0x{rgb565_be(c):04x},  // #{c[0]:02x}{c[1]:02x}{c[2]:02x}")
    lines += ["};", "", "const uint8_t happy_anim_frames[HAPPY_ANIM_FRAMES]"
              "[HAPPY_ANIM_HEIGHT * HAPPY_ANIM_WIDTH] = {"]
    for frame in frames:
        lines.append("    {")
        for y in range(HEIGHT):
            row = frame[y * WIDTH:(y + 1) * WIDTH]
            lines.append("        " + ",".join(str(v) for v in row) + ",")
        lines.append("    },")
    lines += ["};", "", "#endif", ""]
    OUT.write_text("\n".join(lines))

    header = OUT.with_suffix(".h")
    header.write_text("\n".join(HEADER + [
        "// Generated by tools/gen_happy_anim.py from jollybot.gif. Do not edit.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        '#include "sdkconfig.h"',
        "",
        f"#define HAPPY_ANIM_WIDTH     {WIDTH}",
        f"#define HAPPY_ANIM_HEIGHT    {HEIGHT}",
        f"#define HAPPY_ANIM_FRAMES    {len(frames)}",
        f"#define HAPPY_ANIM_FRAME_MS  {durations.pop()}",
        "",
        "#if CONFIG_HOMEHUB_DISPLAY",
        f"extern const uint16_t happy_anim_palette[{len(palette)}];",
        "extern const uint8_t happy_anim_frames[HAPPY_ANIM_FRAMES]"
        "[HAPPY_ANIM_HEIGHT * HAPPY_ANIM_WIDTH];",
        "#endif",
        "",
    ]))
    print(f"{OUT}: {len(frames)} frames, {len(palette)} colours")


if __name__ == "__main__":
    main()
